name: airxiv
channels:
  - pytorch
  - conda-forge
dependencies:
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - arrow-cpp=11.0.0
  - async-timeout=4.0.2
  - attrs=22.2.0
  - aws-c-auth=0.6.26
  - aws-c-cal=0.5.21
  - aws-c-common=0.8.14
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.20
  - aws-c-http=0.7.6
  - aws-c-io=0.13.19
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.7
  - aws-c-sdkutils=0.1.8
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.8
  - aws-sdk-cpp=1.10.57
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - cryptography=40.0.1
  - dataclasses=0.8
  - dataclasses-json=0.5.7
  - datasets=2.11.0
  - dill=0.3.6
  - et_xmlfile=1.1.0
  - filelock=3.11.0
  - flask=2.2.3
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - gflags=2.2.2
  - glog=0.6.0
  - greenlet=2.0.2
  - huggingface_hub=0.13.4
  - idna=3.4
  - importlib-metadata=6.3.0
  - importlib_metadata=6.3.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - krb5=1.20.1
  - langchain=0.0.136
  - libabseil=20230125.0
  - libarrow=11.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.88.1
  - libcxx=16.0.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  # - libgfortran=5.0.0
  # - libgfortran5=12.2.0
  - libgoogle-cloud=2.8.0
  - libgrpc=1.52.1
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libthrift=0.18.1
  - libutf8proc=2.8.0
  - libzlib=1.2.13
  - llvm-openmp=16.0.1
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - marshmallow=3.19.0
  - marshmallow-enum=1.5.1
  - multidict=6.0.4
  - multiprocess=0.70.14
  - mypy_extensions=1.0.0
  - ncurses=6.3
  - nltk=3.8.1
  - numpy=1.24.2
  - openapi-schema-pydantic=1.2.4
  - openpyxl=3.1.1
  - openssl=3.1.0
  - orc=1.8.3
  - packaging=23.0
  - pandas=2.0.0
  - pandas-stubs=1.5.3.230321
  - parquet-cpp=1.5.1
  - pip=23.0.1
  - platformdirs=3.2.0
  - pooch=1.7.0
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydantic=1.10.7
  - pygments=2.15.0
  - pyopenssl=23.1.1
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.2.0
  - python_abi=3.11
  - pytz=2023.3
  - pyyaml=6.0
  - re2=2023.02.02
  - readline=8.2
  - regex=2023.3.23
  - requests=2.28.2
  - responses=0.18.0
  - sacremoses=0.0.53
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=67.6.1
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sqlalchemy=1.4.46
  - stringcase=1.2.0
  - tenacity=8.2.2
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tokenizers=0.13.3
  - tqdm=4.65.0
  - transformers=4.27.4
  - types-pytz=2023.3.0.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - typing_inspect=0.8.0
  - tzdata=2023c
  - urllib3=1.26.15
  - werkzeug=2.2.3
  - wheel=0.40.0
  - xxhash=0.8.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - faiss-cpu==1.7.3
      - mpmath==1.3.0
      - networkx==3.1
      - openai==0.27.4
      - pillow==9.5.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.98
      - sympy==1.11.1
      - torch==2.0.0
      - torchvision==0.15.1
